### ISSUE TITLE
Validating Existing Files Linux Error

### ISSUE THREAD

**Issue by Protektor-Desura** [desura/Desurium#34]
The Linux client has a bug where if the directory for a game exists and is empty it gets stuck at "Validating Existing Files". If you cancel out then the client crashes. You have to go in and delete the empty directory for it to be able to download the game.

**Comment by Jookia** [comment]
Could you find the code where it goes through that stage?

Does it happen if you have empty subdirectories?
Does it happen if you have an empty text file in it?
Does it happen if you have a normal text file in it?

**Comment by Protektor-Desura** [comment]
It happens for me when desura/common/game-directory exists and there are no files in it.

**Comment by Jookia** [comment]
Alrighty. I'll look in to this tomorrow. Right now I'm helping somebody program a map loader for his game.

**Comment by ghost** [comment]
I tried to crash client in way described above - without success. If possible please provide more info about event's conditions (like game, client OS/arch/version and so on).

**Comment by Protektor-Desura** [comment]
It happens under the Linux client only. I am running the 64-bit version of the client but I don't think that makes a difference. I am running Ubuntu 11.10 but again I don't think that makes a difference.

I have not had this problem with the Windows client. Oh in case you don't know. I am the Desura Game Manager so I do a lot more uploading and downloading with the client than probably anyone else.

**Comment by ghost** [comment]
Nice to meet you :) . I understand that client isn't misbehaving every time you're doing what you described originally. I'll try to crash it but next time this happens to you please check `dmesg' command output for something like this:

[ 4057.758151] desura[3610]: segfault at 7f0df4008960 ip 00007f0e0d0f462b sp 00007fffb8de3040 error 4 in libuicore.so[7f0e0cf25000+550000]

(but of course not necessary with library mentioned above). If something like that will appear it would be nice to have core dump.

**Comment by higuita** [comment]
i also had this problema:

http://www.desura.com/groups/desura/forum/thread/install-stop-on-gathereing-information

i think i have a core file for this problem... i can send it if you want ... its 226MB... but its 8.4MB xz compressed :)

**Comment by ghost** [comment]
Great, please send it compressed here: 6lMU0TYkozuP4fYa@oneiroi.net

**Comment by Protektor-Desura** [comment]
Actually the Linux client exhibits this behavior every single time the directory is empty and you tell it to install the game for that directory. It should be very easy to repeat. It does it every single time for me so I just make sure there are no empty game directories every so often.

**Comment by boskee** [comment]
I believe it may be related to the UtilLinux::getFreeSpace() bug, as that problem has stopped ever since I fixed it in my local checkout. Before, Desura was checking common and .settings folders and failed because it was using relative paths (eg. home/user/desura/common, with first slash missing), and crashed as soon as I clicked the cancel button.

See issue #49

**Comment by Jookia** [comment]
The free space pull request is merged. Can somebody verify if it's fixed?

Wait.. No it isn't. What?

**Comment by Protektor-Desura** [comment]
All you need to do to replicate the error is create an empty directory in common for the game and try to install it and it will hang every single time. At least it does for me on build 520.66.

**Comment by higuita** [comment]
using the latest head, i still have the lock on the "Validating Existing Files" and then the crash when cancel

as Protektor-Desura , for me is also easy to replicate... i'm using slackware64 with kernel .3.2.4 and glibc 2.14.1
i also have the core

**Comment by LiamDawe** [comment]
Can someone point me to where the code for this is located so i can have a look over it? I've decided to try to rack my brains on it for a bit and see if i can understand it.

**Comment by Jookia** [comment]
This hasn't happened for me. Could somebody replicate it? Until then, I'm closing it.

**Comment by LiamDawe** [comment]
It happens for me quite often, can someone point me to where the file validating code is located?

**Comment by Jookia** [comment]
All I can say is to grep for a string, or a language ID.

**Comment by LiamDawe** [comment]
I just tested using up to date code - issue does not happen. I tested by downloading VVVVV (however many, stupid name for a game), deleted the contents, exited desurium (after killing it, waiting, kill again..damn other bug), loaded up, asked to install and no problems it installed inside the same folder.

**Comment by LiamDawe** [comment]
Also tested with osmos, installed, uninstalled, made an osmos folder, installed. No problems at all. All looking good my end and i used to get it a lot.
Test also now with Scoregasm, again no issues with folders existing, unless someone else gets it then I would consider it solved.

**Comment by Jookia** [comment]
Closing the bug, I would like somebody to bisect this one day.

**Comment by karolherbst** [comment]
I think it was closed by your changes Jookia, this xdg stuff
